#!/usr/bin/python

from subprocess import call
import shlex
import subprocess
import urllib
import re

def get_eip():
    url = "http://checkip.dyndns.org"
    request = urllib.urlopen(url).read()
    theIP = re.findall(r"\d{1,3}\.\d{1,3}\.\d{1,3}.\d{1,3}", request)
    return theIP[0] #return ip addy to calling function

print get_eip()
